[build]
builder = "nixpacks"

[deploy]
startCommand = "npm run start"
healthcheckPath = "/health"
healthcheckTimeout = 100
restartPolicyType = "on_failure"
restartPolicyMaxRetries = 10

[variables]
NODE_ENV = "production"
PORT = "3000"
NPM_CONFIG_PRODUCTION = "false"
NODE_VERSION = "20"

# Note: Add your Supabase DATABASE_URL in Railway's environment variables dashboard
# Format: postgresql://postgres:[password]@[host]:[port]/postgres?sslmode=require