[build]
builder = "nixpacks"

[deploy]
startCommand = "npm run start"
healthcheckPath = "/api/health"
healthcheckTimeout = 100
restartPolicyType = "on_failure"
restartPolicyMaxRetries = 10

[variables]
NODE_ENV = "production"
PORT = "3000"
NPM_CONFIG_PRODUCTION = "false"